name:                wai-request-id-benchmarks
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/wai-request-id-benchmarks#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  wai-request-id-benchmarks:
    source-dirs:      src
    main:             Main.hs
